// MARK: Prototype extensions
Array.prototype.random = function () {
  return this[Math.floor((Math.random()*this.length))];
}

// MARK: Sample output data

export const SAMPLE_DATA = {
  "output": [
    {
      "dep": [
        [
          1,
          "compound"
        ],
        [
          2,
          "nsubj"
        ],
        [
          -1,
          "ROOT"
        ],
        [
          6,
          "det"
        ],
        [
          6,
          "amod"
        ],
        [
          6,
          "compound"
        ],
        [
          2,
          "attr"
        ],
        [
          6,
          "prep"
        ],
        [
          11,
          "det"
        ],
        [
          10,
          "compound"
        ],
        [
          11,
          "compound"
        ],
        [
          7,
          "pobj"
        ],
        [
          11,
          "prep"
        ],
        [
          14,
          "det"
        ],
        [
          12,
          "pobj"
        ],
        [
          14,
          "prep"
        ],
        [
          15,
          "pobj"
        ],
        [
          16,
          "punct"
        ],
        [
          16,
          "conj"
        ],
        [
          18,
          "punct"
        ],
        [
          21,
          "compound"
        ],
        [
          18,
          "conj"
        ],
        [
          2,
          "punct"
        ]
      ],
      "lem": [
        "emory",
        "university",
        "be",
        "a",
        "private",
        "research",
        "university",
        "in",
        "the",
        "druid",
        "hills",
        "neighborhood",
        "of",
        "the",
        "city",
        "of",
        "atlanta",
        ",",
        "georgia",
        ",",
        "united",
        "states",
        "."
      ],
      "ner": [
        [
          9,
          11,
          "GPE"
        ],
        [
          16,
          17,
          "GPE"
        ],
        [
          18,
          19,
          "GPE"
        ],
        [
          20,
          22,
          "GPE"
        ]
      ],
      "pos": [
        "NNP",
        "NNP",
        "VBZ",
        "DT",
        "JJ",
        "NN",
        "NN",
        "IN",
        "DT",
        "NNP",
        "NNP",
        "NN",
        "IN",
        "DT",
        "NN",
        "IN",
        "NNP",
        ",",
        "NNP",
        ",",
        "NNP",
        "NNP",
        "."
      ],
      "sid": 0,
      "tok": [
        "Emory",
        "University",
        "is",
        "a",
        "private",
        "research",
        "university",
        "in",
        "the",
        "Druid",
        "Hills",
        "neighborhood",
        "of",
        "the",
        "city",
        "of",
        "Atlanta",
        ",",
        "Georgia",
        ",",
        "United",
        "States",
        "."
      ]
    },
    {
      "dep": [
        [
          1,
          "det"
        ],
        [
          3,
          "nsubjpass"
        ],
        [
          3,
          "auxpass"
        ],
        [
          -1,
          "ROOT"
        ],
        [
          3,
          "prep"
        ],
        [
          6,
          "compound"
        ],
        [
          4,
          "pobj"
        ],
        [
          3,
          "prep"
        ],
        [
          7,
          "pobj"
        ],
        [
          3,
          "prep"
        ],
        [
          9,
          "pobj"
        ],
        [
          10,
          "punct"
        ],
        [
          10,
          "appos"
        ],
        [
          3,
          "agent"
        ],
        [
          17,
          "det"
        ],
        [
          17,
          "compound"
        ],
        [
          17,
          "compound"
        ],
        [
          13,
          "pobj"
        ],
        [
          3,
          "cc"
        ],
        [
          20,
          "auxpass"
        ],
        [
          3,
          "conj"
        ],
        [
          20,
          "prep"
        ],
        [
          21,
          "pobj"
        ],
        [
          22,
          "prep"
        ],
        [
          25,
          "amod"
        ],
        [
          27,
          "compound"
        ],
        [
          27,
          "compound"
        ],
        [
          23,
          "pobj"
        ],
        [
          3,
          "punct"
        ]
      ],
      "lem": [
        "the",
        "university",
        "be",
        "found",
        "as",
        "emory",
        "college",
        "in",
        "1836",
        "in",
        "oxford",
        ",",
        "georgia",
        "by",
        "the",
        "methodist",
        "episcopal",
        "church",
        "and",
        "be",
        "name",
        "in",
        "honor",
        "of",
        "methodist",
        "bishop",
        "john",
        "emory",
        "."
      ],
      "ner": [
        [
          5,
          7,
          "ORG"
        ],
        [
          8,
          9,
          "DATE"
        ],
        [
          10,
          11,
          "GPE"
        ],
        [
          12,
          13,
          "GPE"
        ],
        [
          14,
          18,
          "ORG"
        ],
        [
          24,
          25,
          "GPE"
        ],
        [
          26,
          28,
          "PERSON"
        ]
      ],
      "pos": [
        "DT",
        "NN",
        "VBD",
        "VBN",
        "IN",
        "NNP",
        "NNP",
        "IN",
        "CD",
        "IN",
        "NNP",
        ",",
        "NNP",
        "IN",
        "DT",
        "NNP",
        "NNP",
        "NNP",
        "CC",
        "VBD",
        "VBN",
        "IN",
        "NN",
        "IN",
        "JJ",
        "NN",
        "NNP",
        "NNP",
        "."
      ],
      "sid": 1,
      "tok": [
        "The",
        "university",
        "was",
        "founded",
        "as",
        "Emory",
        "College",
        "in",
        "1836",
        "in",
        "Oxford",
        ",",
        "Georgia",
        "by",
        "the",
        "Methodist",
        "Episcopal",
        "Church",
        "and",
        "was",
        "named",
        "in",
        "honor",
        "of",
        "Methodist",
        "bishop",
        "John",
        "Emory",
        "."
      ]
    },
    {
      "dep": [
        [
          5,
          "prep"
        ],
        [
          0,
          "pobj"
        ],
        [
          5,
          "punct"
        ],
        [
          4,
          "det"
        ],
        [
          5,
          "nsubj"
        ],
        [
          -1,
          "ROOT"
        ],
        [
          5,
          "prep"
        ],
        [
          9,
          "poss"
        ],
        [
          9,
          "amod"
        ],
        [
          6,
          "pobj"
        ],
        [
          9,
          "prep"
        ],
        [
          12,
          "compound"
        ],
        [
          10,
          "pobj"
        ],
        [
          5,
          "cc"
        ],
        [
          15,
          "auxpass"
        ],
        [
          5,
          "conj"
        ],
        [
          15,
          "prep"
        ],
        [
          18,
          "compound"
        ],
        [
          16,
          "pobj"
        ],
        [
          5,
          "punct"
        ]
      ],
      "lem": [
        "in",
        "1915",
        ",",
        "the",
        "college",
        "relocate",
        "to",
        "-PRON-",
        "present",
        "location",
        "in",
        "druid",
        "hills",
        "and",
        "be",
        "recharter",
        "as",
        "emory",
        "university",
        "."
      ],
      "ner": [
        [
          1,
          2,
          "DATE"
        ],
        [
          11,
          13,
          "GPE"
        ],
        [
          17,
          19,
          "ORG"
        ]
      ],
      "pos": [
        "IN",
        "CD",
        ",",
        "DT",
        "NN",
        "VBD",
        "IN",
        "PRP$",
        "JJ",
        "NN",
        "IN",
        "NNP",
        "NNP",
        "CC",
        "VBD",
        "VBN",
        "IN",
        "NNP",
        "NNP",
        "."
      ],
      "sid": 2,
      "tok": [
        "In",
        "1915",
        ",",
        "the",
        "college",
        "relocated",
        "to",
        "its",
        "present",
        "location",
        "in",
        "Druid",
        "Hills",
        "and",
        "was",
        "rechartered",
        "as",
        "Emory",
        "University",
        "."
      ]
    },
    {
      "dep": [
        [
          1,
          "det"
        ],
        [
          2,
          "nsubj"
        ],
        [
          -1,
          "ROOT"
        ],
        [
          8,
          "det"
        ],
        [
          6,
          "advmod"
        ],
        [
          6,
          "punct"
        ],
        [
          8,
          "amod"
        ],
        [
          8,
          "amod"
        ],
        [
          2,
          "attr"
        ],
        [
          8,
          "prep"
        ],
        [
          11,
          "amod"
        ],
        [
          9,
          "pobj"
        ],
        [
          8,
          "prep"
        ],
        [
          12,
          "pobj"
        ],
        [
          12,
          "cc"
        ],
        [
          12,
          "conj"
        ],
        [
          20,
          "det"
        ],
        [
          18,
          "advmod"
        ],
        [
          20,
          "amod"
        ],
        [
          20,
          "amod"
        ],
        [
          15,
          "pobj"
        ],
        [
          20,
          "prep"
        ],
        [
          24,
          "det"
        ],
        [
          24,
          "compound"
        ],
        [
          21,
          "pobj"
        ],
        [
          2,
          "punct"
        ]
      ],
      "lem": [
        "the",
        "university",
        "be",
        "the",
        "second",
        "-",
        "old",
        "private",
        "institution",
        "of",
        "high",
        "education",
        "in",
        "georgia",
        "and",
        "among",
        "the",
        "fifty",
        "old",
        "private",
        "university",
        "in",
        "the",
        "united",
        "states",
        "."
      ],
      "ner": [
        [
          4,
          5,
          "ORDINAL"
        ],
        [
          13,
          14,
          "GPE"
        ],
        [
          17,
          18,
          "CARDINAL"
        ],
        [
          22,
          25,
          "GPE"
        ]
      ],
      "pos": [
        "DT",
        "NN",
        "VBZ",
        "DT",
        "RB",
        "HYPH",
        "JJS",
        "JJ",
        "NN",
        "IN",
        "JJR",
        "NN",
        "IN",
        "NNP",
        "CC",
        "IN",
        "DT",
        "CD",
        "JJS",
        "JJ",
        "NNS",
        "IN",
        "DT",
        "NNP",
        "NNP",
        "."
      ],
      "sid": 3,
      "tok": [
        "The",
        "university",
        "is",
        "the",
        "second",
        "-",
        "oldest",
        "private",
        "institution",
        "of",
        "higher",
        "education",
        "in",
        "Georgia",
        "and",
        "among",
        "the",
        "fifty",
        "oldest",
        "private",
        "universities",
        "in",
        "the",
        "United",
        "States",
        "."
      ]
    },
    {
      "dep": [
        [
          1,
          "compound"
        ],
        [
          2,
          "nsubj"
        ],
        [
          -1,
          "ROOT"
        ],
        [
          5,
          "nummod"
        ],
        [
          5,
          "amod"
        ],
        [
          2,
          "dobj"
        ],
        [
          5,
          "punct"
        ],
        [
          8,
          "compound"
        ],
        [
          5,
          "appos"
        ],
        [
          8,
          "prep"
        ],
        [
          9,
          "pobj"
        ],
        [
          10,
          "cc"
        ],
        [
          10,
          "conj"
        ],
        [
          8,
          "punct"
        ],
        [
          15,
          "compound"
        ],
        [
          8,
          "conj"
        ],
        [
          15,
          "punct"
        ],
        [
          18,
          "compound"
        ],
        [
          19,
          "compound"
        ],
        [
          15,
          "conj"
        ],
        [
          19,
          "punct"
        ],
        [
          23,
          "compound"
        ],
        [
          23,
          "compound"
        ],
        [
          19,
          "conj"
        ],
        [
          23,
          "punct"
        ],
        [
          23,
          "conj"
        ],
        [
          25,
          "prep"
        ],
        [
          26,
          "pobj"
        ],
        [
          25,
          "punct"
        ],
        [
          25,
          "conj"
        ],
        [
          29,
          "prep"
        ],
        [
          30,
          "pobj"
        ],
        [
          29,
          "punct"
        ],
        [
          36,
          "compound"
        ],
        [
          36,
          "compound"
        ],
        [
          36,
          "compound"
        ],
        [
          29,
          "conj"
        ],
        [
          36,
          "prep"
        ],
        [
          37,
          "pobj"
        ],
        [
          36,
          "punct"
        ],
        [
          41,
          "compound"
        ],
        [
          36,
          "conj"
        ],
        [
          41,
          "prep"
        ],
        [
          44,
          "compound"
        ],
        [
          42,
          "pobj"
        ],
        [
          41,
          "punct"
        ],
        [
          41,
          "cc"
        ],
        [
          49,
          "det"
        ],
        [
          49,
          "compound"
        ],
        [
          41,
          "conj"
        ],
        [
          49,
          "prep"
        ],
        [
          50,
          "pobj"
        ],
        [
          2,
          "punct"
        ]
      ],
      "lem": [
        "emory",
        "university",
        "have",
        "nine",
        "academic",
        "division",
        ":",
        "emory",
        "college",
        "of",
        "arts",
        "and",
        "sciences",
        ",",
        "oxford",
        "college",
        ",",
        "goizueta",
        "business",
        "school",
        ",",
        "laney",
        "graduate",
        "school",
        ",",
        "school",
        "of",
        "law",
        ",",
        "school",
        "of",
        "medicine",
        ",",
        "nell",
        "hodgson",
        "woodruff",
        "school",
        "of",
        "nursing",
        ",",
        "rollins",
        "school",
        "of",
        "public",
        "health",
        ",",
        "and",
        "the",
        "candler",
        "school",
        "of",
        "theology",
        "."
      ],
      "ner": [
        [
          3,
          4,
          "CARDINAL"
        ],
        [
          7,
          16,
          "ORG"
        ],
        [
          17,
          20,
          "ORG"
        ],
        [
          21,
          28,
          "ORG"
        ],
        [
          29,
          32,
          "ORG"
        ],
        [
          40,
          45,
          "ORG"
        ],
        [
          47,
          52,
          "ORG"
        ]
      ],
      "pos": [
        "NNP",
        "NNP",
        "VBZ",
        "CD",
        "JJ",
        "NNS",
        ":",
        "NNP",
        "NNP",
        "IN",
        "NNPS",
        "CC",
        "NNPS",
        ",",
        "NNP",
        "NNP",
        ",",
        "NNP",
        "NNP",
        "NNP",
        ",",
        "NNP",
        "NNP",
        "NNP",
        ",",
        "NNP",
        "IN",
        "NNP",
        ",",
        "NNP",
        "IN",
        "NNP",
        ",",
        "NNP",
        "NNP",
        "NNP",
        "NNP",
        "IN",
        "NNP",
        ",",
        "NNP",
        "NNP",
        "IN",
        "NNP",
        "NNP",
        ",",
        "CC",
        "DT",
        "NNP",
        "NNP",
        "IN",
        "NNP",
        "."
      ],
      "sid": 4,
      "tok": [
        "Emory",
        "University",
        "has",
        "nine",
        "academic",
        "divisions",
        ":",
        "Emory",
        "College",
        "of",
        "Arts",
        "and",
        "Sciences",
        ",",
        "Oxford",
        "College",
        ",",
        "Goizueta",
        "Business",
        "School",
        ",",
        "Laney",
        "Graduate",
        "School",
        ",",
        "School",
        "of",
        "Law",
        ",",
        "School",
        "of",
        "Medicine",
        ",",
        "Nell",
        "Hodgson",
        "Woodruff",
        "School",
        "of",
        "Nursing",
        ",",
        "Rollins",
        "School",
        "of",
        "Public",
        "Health",
        ",",
        "and",
        "the",
        "Candler",
        "School",
        "of",
        "Theology",
        "."
      ]
    },
    {
      "dep": [
        [
          1,
          "compound"
        ],
        [
          17,
          "nsubj"
        ],
        [
          1,
          "punct"
        ],
        [
          5,
          "det"
        ],
        [
          5,
          "compound"
        ],
        [
          1,
          "appos"
        ],
        [
          5,
          "prep"
        ],
        [
          6,
          "pobj"
        ],
        [
          5,
          "punct"
        ],
        [
          5,
          "cc"
        ],
        [
          11,
          "compound"
        ],
        [
          5,
          "conj"
        ],
        [
          11,
          "prep"
        ],
        [
          12,
          "pobj"
        ],
        [
          1,
          "punct"
        ],
        [
          17,
          "nsubj"
        ],
        [
          17,
          "advmod"
        ],
        [
          -1,
          "ROOT"
        ],
        [
          22,
          "det"
        ],
        [
          22,
          "compound"
        ],
        [
          22,
          "compound"
        ],
        [
          22,
          "compound"
        ],
        [
          17,
          "dobj"
        ],
        [
          22,
          "prep"
        ],
        [
          25,
          "compound"
        ],
        [
          23,
          "pobj"
        ],
        [
          17,
          "punct"
        ]
      ],
      "lem": [
        "emory",
        "university",
        ",",
        "the",
        "georgia",
        "institute",
        "of",
        "technology",
        ",",
        "and",
        "peking",
        "university",
        "in",
        "beijing",
        ",",
        "china",
        "jointly",
        "administer",
        "the",
        "wallace",
        "h.",
        "coulter",
        "department",
        "of",
        "biomedical",
        "engineering",
        "."
      ],
      "ner": [
        [
          3,
          8,
          "ORG"
        ],
        [
          10,
          12,
          "ORG"
        ],
        [
          13,
          14,
          "GPE"
        ],
        [
          15,
          16,
          "GPE"
        ],
        [
          18,
          26,
          "ORG"
        ]
      ],
      "pos": [
        "NNP",
        "NNP",
        ",",
        "DT",
        "NNP",
        "NNP",
        "IN",
        "NNP",
        ",",
        "CC",
        "NNP",
        "NNP",
        "IN",
        "NNP",
        ",",
        "NNP",
        "RB",
        "VBP",
        "DT",
        "NNP",
        "NNP",
        "NNP",
        "NNP",
        "IN",
        "NNP",
        "NNP",
        "."
      ],
      "sid": 5,
      "tok": [
        "Emory",
        "University",
        ",",
        "the",
        "Georgia",
        "Institute",
        "of",
        "Technology",
        ",",
        "and",
        "Peking",
        "University",
        "in",
        "Beijing",
        ",",
        "China",
        "jointly",
        "administer",
        "the",
        "Wallace",
        "H.",
        "Coulter",
        "Department",
        "of",
        "Biomedical",
        "Engineering",
        "."
      ]
    },
    {
      "dep": [
        [
          1,
          "det"
        ],
        [
          2,
          "nsubj"
        ],
        [
          -1,
          "ROOT"
        ],
        [
          5,
          "det"
        ],
        [
          5,
          "compound"
        ],
        [
          2,
          "dobj"
        ],
        [
          5,
          "prep"
        ],
        [
          6,
          "pobj"
        ],
        [
          2,
          "prep"
        ],
        [
          8,
          "pobj"
        ],
        [
          9,
          "prep"
        ],
        [
          12,
          "compound"
        ],
        [
          10,
          "pobj"
        ],
        [
          2,
          "punct"
        ]
      ],
      "lem": [
        "the",
        "university",
        "operate",
        "the",
        "confucius",
        "institute",
        "in",
        "atlanta",
        "in",
        "partnership",
        "with",
        "nanjing",
        "university",
        "."
      ],
      "ner": [
        [
          3,
          6,
          "ORG"
        ],
        [
          7,
          8,
          "GPE"
        ],
        [
          11,
          13,
          "ORG"
        ]
      ],
      "pos": [
        "DT",
        "NN",
        "VBZ",
        "DT",
        "NNP",
        "NNP",
        "IN",
        "NNP",
        "IN",
        "NN",
        "IN",
        "NNP",
        "NNP",
        "."
      ],
      "sid": 6,
      "tok": [
        "The",
        "university",
        "operates",
        "the",
        "Confucius",
        "Institute",
        "in",
        "Atlanta",
        "in",
        "partnership",
        "with",
        "Nanjing",
        "University",
        "."
      ]
    },
    {
      "dep": [
        [
          1,
          "nsubj"
        ],
        [
          -1,
          "ROOT"
        ],
        [
          6,
          "det"
        ],
        [
          6,
          "amod"
        ],
        [
          5,
          "compound"
        ],
        [
          6,
          "compound"
        ],
        [
          1,
          "dobj"
        ],
        [
          6,
          "prep"
        ],
        [
          11,
          "det"
        ],
        [
          11,
          "compound"
        ],
        [
          11,
          "compound"
        ],
        [
          7,
          "pobj"
        ],
        [
          11,
          "prep"
        ],
        [
          12,
          "pobj"
        ],
        [
          13,
          "cc"
        ],
        [
          13,
          "conj"
        ],
        [
          17,
          "punct"
        ],
        [
          11,
          "appos"
        ],
        [
          17,
          "punct"
        ],
        [
          1,
          "punct"
        ]
      ],
      "lem": [
        "emory",
        "have",
        "a",
        "grow",
        "faculty",
        "research",
        "partnership",
        "with",
        "the",
        "korea",
        "advanced",
        "institute",
        "of",
        "science",
        "and",
        "technology",
        "(",
        "kaist",
        ")",
        "."
      ],
      "ner": [
        [
          8,
          16,
          "ORG"
        ]
      ],
      "pos": [
        "NNP",
        "VBZ",
        "DT",
        "VBG",
        "NN",
        "NN",
        "NN",
        "IN",
        "DT",
        "NNP",
        "NNP",
        "NNP",
        "IN",
        "NNP",
        "CC",
        "NNP",
        "-LRB-",
        "NNP",
        "-RRB-",
        "."
      ],
      "sid": 7,
      "tok": [
        "Emory",
        "has",
        "a",
        "growing",
        "faculty",
        "research",
        "partnership",
        "with",
        "the",
        "Korea",
        "Advanced",
        "Institute",
        "of",
        "Science",
        "and",
        "Technology",
        "(",
        "KAIST",
        ")",
        "."
      ]
    },
    {
      "dep": [
        [
          1,
          "compound"
        ],
        [
          2,
          "compound"
        ],
        [
          3,
          "nsubj"
        ],
        [
          -1,
          "ROOT"
        ],
        [
          3,
          "prep"
        ],
        [
          7,
          "det"
        ],
        [
          7,
          "nummod"
        ],
        [
          4,
          "pobj"
        ],
        [
          7,
          "punct"
        ],
        [
          10,
          "nummod"
        ],
        [
          3,
          "npadvmod"
        ],
        [
          10,
          "prep"
        ],
        [
          14,
          "det"
        ],
        [
          14,
          "compound"
        ],
        [
          11,
          "pobj"
        ],
        [
          10,
          "punct"
        ],
        [
          10,
          "cc"
        ],
        [
          18,
          "quantmod"
        ],
        [
          20,
          "nummod"
        ],
        [
          20,
          "amod"
        ],
        [
          10,
          "conj"
        ],
        [
          3,
          "punct"
        ]
      ],
      "lem": [
        "emory",
        "university",
        "student",
        "come",
        "from",
        "all",
        "50",
        "state",
        ",",
        "6",
        "territory",
        "of",
        "the",
        "united",
        "states",
        ",",
        "and",
        "over",
        "100",
        "foreign",
        "country",
        "."
      ],
      "ner": [
        [
          6,
          7,
          "CARDINAL"
        ],
        [
          9,
          10,
          "CARDINAL"
        ],
        [
          12,
          15,
          "GPE"
        ],
        [
          17,
          19,
          "CARDINAL"
        ]
      ],
      "pos": [
        "NNP",
        "NNP",
        "NNS",
        "VBP",
        "IN",
        "DT",
        "CD",
        "NNS",
        ",",
        "CD",
        "NNS",
        "IN",
        "DT",
        "NNP",
        "NNP",
        ",",
        "CC",
        "IN",
        "CD",
        "JJ",
        "NNS",
        "."
      ],
      "sid": 8,
      "tok": [
        "Emory",
        "University",
        "students",
        "come",
        "from",
        "all",
        "50",
        "states",
        ",",
        "6",
        "territories",
        "of",
        "the",
        "United",
        "States",
        ",",
        "and",
        "over",
        "100",
        "foreign",
        "countries",
        "."
      ]
    }
  ],
  "pipeline": {
    "dep": "spacy",
    "lem": "spacy",
    "ner": "spacy",
    "pos": "spacy",
    "tok": "spacy"
  }
};
